### ISSUE TITLE
Prometheus config file example

### ISSUE THREAD

**Issue by boxerwba** [nshttpd/mikrotik-exporter#122]
Can someone provide own Prometheus config file?
![image](https://user-images.githubusercontent.com/43293067/136077422-0ec64f29-ab9d-414b-b682-12b2ed982dfb.png)
I want to scrape metrics from two mikrotik. 
Here is my non-working prom config:
`
  - job_name: 'mikrotik1'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 10.10.75.1
    metrics_path: /metrics
    params:
      module: [my_router]

  - job_name: 'mikrotik2'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 10.10.74.1
    metrics_path: /metrics
    params:
      module: [my_router]
`

**Comment by lisenet** [comment]
This is my config that works:
```
      - job_name: 'mikrotik-exporter'
        scrape_interval: 30s
        static_configs:
          - targets:
            - 10.11.1.1 # your Mikrotik router IP you wish to monitor
        metrics_path: /metrics
        params:
          module: [my_router]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: mikrotik-exporter:9436
```
