### ISSUE TITLE
Collect error parsing interface metric value

### ISSUE THREAD

**Issue by risewo2997** [nshttpd/mikrotik-exporter#134]
I use docker.
image: nshttpd/mikrotik-exporter-linux-arm64:1.0.11

And I get an error.
**Error:**
```
{"device":"device-name","error":"strconv.ParseFloat: parsing \"\": invalid syntax","interface":"interface-name","level":"error","msg":"error parsing interface metric value","property":"overall-tx-ccq","time":"2001-01-01T01:01:01Z"}
```

**config.yml:**
```
devices:
  - name: Mikrotik
    address: 127.0.0.1
    user: user
    password: password

features:
  wlanif: true
```

**Part response from /metrics:**
```
...
# HELP mikrotik_wlan_interface_overall_tx_ccq overall-tx-ccq
# TYPE mikrotik_wlan_interface_overall_tx_ccq gauge
mikrotik_wlan_interface_overall_tx_ccq{address="127.0.0.1",channel="2447/20-Ce/gn(20dBm)",interface="wlan100",name="name"} 96
...
```
