### ISSUE TITLE
Help me get on docker synology

### ISSUE THREAD

**Issue by BorzDev** [nshttpd/mikrotik-exporter#156]
Can someone write docker-compose to install on Synology nas...

**Comment by BorzDev** [comment]
/docker/mikrotik-exporter/config.yml  
```
devices:
  - name: my_router
    address: 192.168.8.1
    user: prometheus
    password: Yyy0123

features:
  bgp: true
  dhcp: true
  dhcpv6: false
  dhcpl: true
  routes: true
  pools: true
  optics: true
```
