### ISSUE TITLE
Better log to explain what happened

### ISSUE THREAD

**Issue by DanielYWoo** [nshttpd/mikrotik-exporter#80]
This is my first time to use this exporter and I have a very simple configuration file like this

```
devices:
  - name: xxx
    address: xxx
    user: xxx
    password: xxx

features:
  bgp: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
```
As I run the exporter, the log shows some error but no detailed information for me to continue to dig in.
```
{"level":"error","msg":"Could not load config: missing required param for single device configuration","time":"2020-03-31T17:15:34Z"}
```

Can we add more info in case of an error?
