### ISSUE TITLE
System temperature and voltage

### ISSUE THREAD

**Issue by runningman84** [nshttpd/mikrotik-exporter#83]
It would be great to get the system temperature and voltage.

**Comment by jimbrowne** [comment]
It does:
```# HELP mikrotik_health_temperature Temperature of RouterOS board, in degrees Celsius
# TYPE mikrotik_health_temperature gauge
mikrotik_health_temperature{address="xx.yy.zz.10",name="xx-yy-zz-1"} 41
mikrotik_health_temperature{address="aa.bb.cc",name="aa-bb-cc-2"} 45
# HELP mikrotik_health_voltage Input voltage to the RouterOS board, in volts
# TYPE mikrotik_health_voltage gauge
mikrotik_health_voltage{address="xx.yy.zz.10",name="xx-yy-zz-1"} 23
mikrotik_health_voltage{address="aa.bb.cc",name="aa-bb-cc-2"} 26.6
```

However those values are not present on hardware that does not support them, like running RouterOS on off the shelf x86 hardware.  It think there's also a bug on some CRS devices with SNMP and temperature, so perhaps that is related.

Were you trying this with a particular piece of hardware?

**Comment by runningman84** [comment]
I am using a hEX

**Comment by jimbrowne** [comment]
Are you invoking with `-with-health` or including: `health: true` in the `features:` section of your config file?

**Comment by tbendiksen** [comment]
For reference this does work for me on the following devices:
crs112
rb4011
rb962

**Comment by WireFuCo** [comment]
i cant seem to get this to work, i have the following in my config file:

```yaml
devices:
  - name: router
    address: xxx
    user: xxx
    password: xxx
    log-level: debug

features:
  BGP: true
  DHCP: true
  DHCPL: true
  Health: true
  Firmware: true
  #routes: true
  Optics: true
  POE: true
  Monitor: true
```
also tried with lowercase. it just doesnt seem to be pulling this in. In particular i cant see the health data.  Not sure where im going wrong :( using Docker
