### ISSUE TITLE
Wlan stats not visible

### ISSUE THREAD

**Issue by kad-beumer** [nshttpd/mikrotik-exporter#86]
Helo,

Thnx for the exporter, except I have one issue. Although I enabled features WLAN-station and Wlan interface I do not see any information for these features in my prometheus.

Am I missing something?

**Comment by shtouff** [comment]
cf config/config.test.yml:

```
 features:
  bgp: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
  wlansta: true
  wlanif: true
  ipsec: true
```

Did you add wlan* to your config ? It adds some wlan related metrics, but not all those that are needed to display this dashboard: https://grafana.com/grafana/dashboards/10950

**Comment by kad-beumer** [comment]
I use below config and see no WLAN related config in my dashboard

```
    features:
      bgp: true
      dhcp: true
      dhcpv6: true
      dhcp-leases: true
      routes: true
      routesv6: true
      pool: true
      poolv6: true
      optics: true
      wlan-interfaces: true
      wlan-stations: true
      monitor: true
      ipsec-peers: true
      ospf-neighbor: true
```
