### ISSUE TITLE
Example prometheus.yml

### ISSUE THREAD

**Issue by michael-robbins** [nshttpd/mikrotik-exporter#94]
Does anyone have an example prometheus.yml scrape_configs?

Eg:
```
scrape_configs:
  - job_name: "mikrotik_exporter"
    static_configs:
      - targets: ["localhost:9436"]
```

Most other ones I have, have a `relabel_configs` key as well, is there any extra configuration I need to provide?
