### ISSUE TITLE
collector failed - from RouterOS device: no such command prefix

### ISSUE THREAD

**Issue by nagylzs** [nshttpd/mikrotik-exporter#96]
RouterOS 6.47.4, model RBD52G-5HacD2HnD (HAP-AC2) encounters an error while collecting data.

mikrotik-exporter config:

```
devices:
  - name: router.example.com
    address: router.example.com
    user: some_user_not_telling
    password: ********

features:
  bgp: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
```

Collector logs this error:

```
{"level":"error","msg":"ERROR: router.example.com collector failed after 0.458261s: from RouterOS device: no such command prefix","time":"2020-10-13T09:27:34Z"}
```
